### PR TITLE
Fix #1638

### LINKED ISSUE #1638: wrong file download on https://www.ekn.io/calendar/
- **Min Version:** 1.19.2
- **Operating system:** Windows 10

## Expected Behavior
it should let me download pdf file

## Actual Behavior
it downloads wrong file which is not pdf

## To Reproduce

go to this https://www.ekn.io/calendar/ and enter some date, press Download Calendar then it will open new page that doesnot load and download.html will appear in downloads bar

### PR DESCRIPTION
**Pull request by lubiedo**
Check if `Content-Disposition` header is provided and: if exists and defined as `attachment` then download the PDF, if not then use the PDF viewer.

### CODE REVIEW

File: main/download.js [hunk 1]
```diff
@@ -54,7 +60,9 @@ function listenForPDFDownload (ses) {
   ses.webRequest.onHeadersReceived(function (details, callback) {
     if (details.resourceType === 'mainFrame' && details.responseHeaders) {
       var typeHeader = details.responseHeaders[Object.keys(details.responseHeaders).filter(k => k.toLowerCase() === 'content-type')]
-      if (typeHeader instanceof Array && typeHeader.filter(t => t.includes('application/pdf')).length > 0 && details.url.indexOf('#pdfjs.action=download') === -1) {
+      var attachment = isAttachment(details.responseHeaders[Object.keys(details.responseHeaders).filter(k => k.toLowerCase() === 'content-disposition')])
```
Comment (PalmerAL) [inline main/download.js:63]: Learned something new here :) I didn't know you could use an array to look up an object property like this, but I guess it works:
```
var x = {a: 1}
var y = x[["a"]] // = 1
```
It even works with nested arrays:
```
var y = x[[[[[["a"]]]]]] // = 1

**Comment by PalmerAL** [comment]
Looks great, thanks!
