### PR TITLE
Fix incorrect scrolling on mod + scroll zoom

### LINKED ISSUE #127: Pinch to Zoom
The current zooming solution (cmd + scroll) is clunky and scrolls while zooming. Implementing pinch to zoom would make it much more intuitive for users of apple laptops.

### PR DESCRIPTION
**Pull request by revolter**
Fixes #127

### CODE REVIEW

File: js/webview/swipeEvents.js [hunk 1]
```diff
@@ -8,6 +8,9 @@ var beginningScrollRight = null
 
 var hasShownSwipeArrow  = false
 
+// TODO: find out a way to read this from settings
+var isZoomWithScrollEnabled = true
```
Comment (revolter) [inline js/webview/swipeEvents.js]: @PalmerAL, Could you please help me figure out how to read the respective setting's value in this file?

Comment (PalmerAL) [reply js/webview/swipeEvents.js]: @revolter You can't, because you can only read from the database in a page with a file:/// origin. The way we worked around this for the swipe preference was to send an IPC to the parent process, which would then check the preference and do the navigation. (the code for this is here: https://github.com/minbrowser/min/blob/master/js/webviews.js#L272-L278). I'm guessing you'd have to do something similar here.

**Comment by PalmerAL** [comment]
I guess we could add this if we really have to, but I'd prefer to find a way to fix the original issue instead. If we just add a preference, most people aren't even going to notice it, and if you turn it on you lose the functionality entirely. Is there some other way we could detect whether the page is actually being scrolled?

**Comment by revolter** [comment]
@PalmerAL, I rebased the entire branch and only left the minor spelling fix, grunt task simplifier ❤️ and the #127 fix.

**Comment by PalmerAL** [comment]
@revolter Looks good, thanks! I think I have an idea about how to fix #89, I'll add a comment to that issue.
